---
- name: Copy charon-german-dc.conf
  become: true
  template:
    src: charon.conf.j2
    dest: "/etc/strongswan.d/charon-{{ role_name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart ipsec

- name: Import ipsec_gateway configuration
  become: true
  lineinfile:
    path: /etc/ipsec.conf
    state: present
    regexp: "^include {{ vpn_gateway_config_dir + '/*.conf' | regex_escape }}$"
    line: "include {{ vpn_gateway_config_dir }}/*.conf"
  notify: Restart ipsec

- name: Import ipsec_gateway secrets
  become: true
  lineinfile:
    path: /etc/ipsec.secrets
    state: present
    regexp: "^include {{ vpn_gateway_config_dir + '/*.secrets' | regex_escape }}$"
    line: "include {{ vpn_gateway_config_dir }}/*.secrets"
  notify: Restart ipsec

- name: Create /etc/ipsec.d/nl2go.ipsec_gateway/ directory
  become: true
  file:
    path: "{{ vpn_gateway_config_dir }}"
    owner: root
    group: root
    state: directory
  notify: Restart ipsec

- name: Copy ipsec.conf
  become: true
  template:
    src: ipsec.conf.j2
    dest: "{{ vpn_gateway_config_dir }}/ipsec.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart ipsec

- name: Copy ipsec.secrets
  become: true
  template:
    src: ipsec.secrets.j2
    dest: "{{ vpn_gateway_config_dir }}/ipsec.secrets"
    owner: root
    group: root
    mode: 0600
  notify: Reload ipsec secrets

# FIXME: this fails in Ubuntu 16.04 but strongswan instead works in u16 and u18:
#- name: IPSec must be running
#  service:
#    name: ipsec
#    state: started

- name: IPSec must be running
  service:
    name: strongswan
    state: started
