---
- name: Install strongswan
  become: true
  package:
    name:
      - strongswan
      - libstrongswan-standard-plugins
  when: vpn_gateway_vpns is defined and vpn_gateway_vpns.site_to_site is defined
