---
- name: Install tools
  package:
    name:
      - netfilter-persistent
      - iptables-persistent
    state: present

- name: Set required sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ sysctl_config | dict2items }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1

- name: Upload firewall rules
  template:
    src: iptables-rules.j2
    dest: /tmp/iptables-rules
    mode: '0444'

- name: Load firewall rules
  shell: |
    set -o pipefail
    cat /tmp/iptables-rules | iptables-restore
  args:
    executable: /bin/bash
  changed_when: False
