---
- name: Configure a gateway
  hosts: all
  gather_facts: no
  become: true
  user: root
  pre_tasks:
    - name: Only run "update_cache=yes" if the last one is older than 1 day.
      apt:
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - role: ansible-role-vpn-gateway
