---
scenario:
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
  driver:
    name: docker
  lint:
    name: yamllint
platforms:
# FIXME: don't forget to test in all platforms.
#  - name: debian9
#    image: debian:9
#    dockerfile: ../resources/Dockerfile.j2
#    capabilities:
#      - NET_ADMIN
#    groups:
#      - platforms
#  - name: debian10
#    image: debian:10
#    dockerfile: ../resources/Dockerfile.j2
#    capabilities:
#      - NET_ADMIN
#    groups:
#      - platforms
#  - name: Ubuntu16
#    image: ubuntu:16.04
#    dockerfile: ../resources/Dockerfile.j2
#    capabilities:
#      - NET_ADMIN
#    groups:
#      - platforms
  - name: Ubuntu18
    image: ubuntu:18.04
    dockerfile: ../resources/Dockerfile.j2
    groups:
      - platforms
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vpn_gateway_configs:
          - name: default
            psk: corona-hamster
            local:
              public: 2.5.7.8
              private: 172.4.0.20
              private_interface: eth6
              networks:
                - 172.4.0.0/21
            remote:
              public: 1.2.3.4
              networks:
                - 172.240.0.0/21
                - 10.2.0.0/16
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    cleanup: ../resources/playbooks/cleanup.yml
verifier:
  name: testinfra
#  env:
#    FOO: "bar"
  lint:
    name: flake8
