---
- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Install netaddr package
      pip:
        name: netaddr
    - name: Ensure SSH control path directoy exists
      file:
        path: "{{ lookup('env','HOME') }}/.ansible/cp"
        state: directory
        mode: '0755'

- name: Prepare hosts
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache if required
      apt:
        update_cache: yes
        cache_valid_time: 86400
