---
- name: Verify
  hosts: all
  tasks:
    - name: Is IP Forwarding configured?
      shell: grep '^1$' /proc/sys/net/ipv4/ip_forward  # noqa 301
      register: result
    - name: Confirm that IP Forwarding is on.
      assert:
        that:
          - result is defined
          - result.failed is defined
          - not result.failed

    - name: look for ipsec service
      shell: service strongswan status  # noqa 301 305
      args:
        warn: false
      ignore_errors: yes
      register: result
      # NOTE: it returns 4 if ``Unit ipsec.service could not be found.`` (i.e. not installed)
      # NOTE: it returns 3 if the service is inactive (e.g. installed but can't connect, what is the expected result here)
      # NOTE: it returns 0 if the service is running as usual.
    - name: Confirm that the service is somehow there
      assert:
        that:
          - result is defined
          - result.rc is defined
          - result.rc != 4
